"use strict";

const sampleRenewals = {
  checkedAt: "2026-05-31T09:15:00.000Z",
  policy: {
    defaultMaxIncreaseBps: 800,
    minimumNoticeDays: 45,
    maxCpiStalenessDays: 120,
    maxUnsupportedIncreaseBps: 0,
  },
  renewals: [
    {
      id: "ren-clean-cpi",
      customer: "Northlake Genomics Lab",
      segment: "institutional",
      renewalDate: "2026-08-01",
      currentAnnualCents: 1200000,
      proposedAnnualCents: 1260000,
      contract: {
        upliftCapBps: 600,
        priceLockUntil: "2026-07-31",
        requiresNoticeDays: 45,
        excludedFromAutoUplift: false,
      },
      cpiEvidence: { source: "national-statistics-office", valueBps: 490, observedAt: "2026-04-30" },
      notice: { sentAt: "2026-05-31", channel: "billing-admin-email" },
      approval: null,
    },
    {
      id: "ren-over-cap",
      customer: "East Harbor Quant Lab",
      segment: "institutional",
      renewalDate: "2026-07-15",
      currentAnnualCents: 900000,
      proposedAnnualCents: 1017000,
      contract: {
        upliftCapBps: 800,
        priceLockUntil: "2026-06-30",
        requiresNoticeDays: 45,
        excludedFromAutoUplift: false,
      },
      cpiEvidence: { source: "national-statistics-office", valueBps: 520, observedAt: "2026-04-30" },
      notice: { sentAt: "2026-05-31", channel: "billing-admin-email" },
      approval: null,
    },
    {
      id: "ren-stale-cpi",
      customer: "Alpine Neuroimaging Institute",
      segment: "institutional",
      renewalDate: "2026-09-01",
      currentAnnualCents: 460000,
      proposedAnnualCents: 483000,
      contract: {
        upliftCapBps: 700,
        priceLockUntil: "2026-08-31",
        requiresNoticeDays: 45,
        excludedFromAutoUplift: false,
      },
      cpiEvidence: { source: "national-statistics-office", valueBps: 500, observedAt: "2025-12-31" },
      notice: { sentAt: "2026-06-20", channel: "billing-admin-email" },
      approval: null,
    },
    {
      id: "ren-late-notice",
      customer: "Cedar Clinical Trials Office",
      segment: "institutional",
      renewalDate: "2026-07-01",
      currentAnnualCents: 320000,
      proposedAnnualCents: 336000,
      contract: {
        upliftCapBps: 600,
        priceLockUntil: "2026-06-30",
        requiresNoticeDays: 45,
        excludedFromAutoUplift: false,
      },
      cpiEvidence: { source: "national-statistics-office", valueBps: 510, observedAt: "2026-04-30" },
      notice: { sentAt: "2026-05-31", channel: "billing-admin-email" },
      approval: null,
    },
    {
      id: "ren-price-locked",
      customer: "Riverbend Consortium",
      segment: "consortium",
      renewalDate: "2026-08-15",
      currentAnnualCents: 2200000,
      proposedAnnualCents: 2310000,
      contract: {
        upliftCapBps: 500,
        priceLockUntil: "2026-12-31",
        requiresNoticeDays: 60,
        excludedFromAutoUplift: true,
      },
      cpiEvidence: { source: "national-statistics-office", valueBps: 500, observedAt: "2026-04-30" },
      notice: { sentAt: "2026-05-31", channel: "billing-admin-email" },
      approval: { id: "APP-77", approver: "finance-director", reason: "manual consortium renewal exception" },
    },
  ],
};

module.exports = { sampleRenewals };
